### ISSUE TITLE
希望能添加MySQL数据库的支持|Hope to add MySQL database support

### ISSUE THREAD

**Issue by ghost** [neko-craft/NekoGuard#2]
希望能添加针对MySQL数据库的支持，InfluxDB的话远程配置感觉有点麻烦......
I hope to add support for MySQL database, InfluxDB remote configuration feels a bit troublesome......

**Comment by ShirasawaSama** [comment]
无法添加，因为本插件就是为influxdb量身打造的

**Comment by ghost** [comment]
> 无法添加，因为本插件就是为influxdb量身打造的

好吧。。。我试试看远程使用InfluxDB

**Comment by ghost** [comment]
> 无法添加，因为本插件就是为influxdb量身打造的

折腾半天了，远程链接依旧没弄好。。。有没有配置远程链接的教程啊？配置完后一直显示连接超时。。。
